### ISSUE TITLE
Data: Notes are excluded from import

### ISSUE THREAD

**Issue by matjames007** [slashroots/undp-ghg-v2#11]
<img width="466" alt="screen shot 2017-11-11 at 4 56 18 pm" src="https://user-images.githubusercontent.com/1425164/32693904-49458418-c701-11e7-8d01-906db99ba416.png">
When the data import has been done - the notes are not captured and therefore not displayed for user manipulation.

**Comment by gilgad** [comment]
Notes are now being imported and displayed as a field. Additionally notes can be edited for a selected row.

**Comment by matjames007** [comment]
completed.
