### ISSUE TITLE
All activities in the Platform Log have the same time stamp

### ISSUE THREAD

**Issue by densoutar** [slashroots/undp-ghg-v2#51]
User Log Timestamps - All activities listed in the Platform Log on the User Profile page have the same timestamp, despite being done at different times

**Comment by paradoxxjm** [comment]
This issue appears to have been address. @gilgad @denferg can you confirm

**Comment by gilgad** [comment]
this was resolved

**Comment by densoutar** [comment]
@paradoxxjm @gilgad I'm not seeing where this has been resolved:

<img width="1440" alt="screen shot 2018-02-26 at 1 24 47 am" src="https://user-images.githubusercontent.com/15874753/36655991-0b651726-1a94-11e8-83b9-0ae51f968010.png">

**Comment by densoutar** [comment]
Resolved
