### ISSUE TITLE
Data Table Selected Column Highlight Remains off 

### ISSUE THREAD

**Issue by paradoxxjm** [slashroots/undp-ghg-v2#62]
When the user selects a row, the application highlights the row and adds a checkmark to the table. However, the calculation to generate checkmark and the row highlight seem to be off by one. See below:

![ghg-datatable-rowhighlightoffset](https://user-images.githubusercontent.com/406181/36272005-39c686e8-124e-11e8-8436-47b1fbb1d124.png)

**Comment by densoutar** [comment]
@paradoxxjm resolved; please close.
