### ISSUE TITLE
"Closing an Inventory" Feature

### ISSUE THREAD

**Issue by paradoxxjm** [slashroots/undp-ghg-v2#64]
Currently, the application does not allow an inventory manager or admin user to "close" an inventory. A few design considerations that need to be fulfilled for this feature

- Closing an inventory should prevent further changes (e.g modifications to settings, data table, calculations, etc,) by all users.
- Only an Inventory Manager or Administrator should be able to re-open an inventory
- Administrators / Inventory Managers should be allowed to open only one inventory at a time.

@matjames007  Denique, please confirm what other constraints need to be included.

**Comment by matjames007** [comment]
@paradoxxjm this actually exists currently - however the error messaging in the platform requires some work.

**Comment by densoutar** [comment]
Noted @matjames007; but for the record, other constraints: 

- Closed inventories should be visibly tagged as closed in the Data, Calculations and Reporting pages.
- Attempt to re-openan inventory should be confirmed.

**Comment by paradoxxjm** [comment]
@denferg can you confirm.

**Comment by densoutar** [comment]
Partially resolved. Resolved issues are:
- Only admin and manager roles have option to close inventory
- Attempt to close inventory triggers confirmation

Unable to test the following (not sure if closing the inventory would interfere with troubleshooting other issues currently waiting to be addressed): 
- ability to edit a closed inventory
- whether closed inventory is tagged as closed
- whether only an inventory manager or admin can re-open, _after_ confirmation

@gilgad

**Comment by densoutar** [comment]
@gilgad  confirmed it should not be possible to re-open an inventory after an inventory is closed. If values need to be updated, that will be done in the next inventory.

Will consider this issue resolved.
