### ISSUE TITLE
Inconsistent display of significant figures

### ISSUE THREAD

**Issue by densoutar** [slashroots/undp-ghg-v2#65]
Numbers should be displayed according to the same formats (the IPPC has requirements for significant figures). The Calculations page for example displays both rounded off figures and figures to a number of decimal places, making checking calculations confusing.

<img width="1440" alt="screen shot 2018-02-15 at 9 46 59 pm" src="https://user-images.githubusercontent.com/15874753/36291658-693bc9e6-129a-11e8-8b67-3943cc6aa772.png">

**Comment by paradoxxjm** [comment]
@denferg can you provide more specifics as to how you would like @gilgad to modify the precision level for the numbers.

**Comment by densoutar** [comment]
The Calculations AD value is rounded off to far fewer significant figures than all the other values on the Calculations screen.

It appears one standard of rounding is applied to the AD variable values in Data, another to the AD variable values in Calculation, and a third standard to the AD variable _actually_ used in the computation. 

There needs to be one standard for how numbers are displayed and computed, and that needs to be based on the specifications in the IPCC Guidelines (I believe Budram had said this was a thing...at the very least, there is some standard he's using).

**Comment by densoutar** [comment]
Unable to test, as AD values are no longer displayed (see comments on #69).

**Comment by densoutar** [comment]
AD values displayed are consistent with the values used for calculation; marked as pass.
