### ISSUE TITLE
Misleading Four-Way Pointer on Calculations Page

### ISSUE THREAD

**Issue by densoutar** [slashroots/undp-ghg-v2#67]
Normal mouse pointer turns into four-way pointer on Calculations, misleadingly indicating that drag'n'drop interactions are required.

![img_20180215_220005135](https://user-images.githubusercontent.com/15874753/36291904-1825165a-129c-11e8-8563-a7c99fd77e9c.jpg)

**Comment by paradoxxjm** [comment]
@denferg can you confirm that this is now resolved?

**Comment by densoutar** [comment]
Yes; resolved.
