### ISSUE TITLE
More clarifying details required on Calculations page

### ISSUE THREAD

**Issue by densoutar** [slashroots/undp-ghg-v2#69]
Subsumes issues #58 & #59: 

There's not enough differentiating information about the activities, emissions factors and emissions estimate. Recommended changes attached. It includes restructuring the AD and EF labels so that data type, category and activity are listed in the same order, as well as only showing the uncertainty for the emissions.

<img width="1227" alt="revised calculations screen" src="https://user-images.githubusercontent.com/15874753/36292865-cf842df8-12a2-11e8-887e-7598fac846bf.png">

**Comment by paradoxxjm** [comment]
@gilgad see the recommended UI modifications for labels of the calculations window.

**Comment by densoutar** [comment]
A number of key features of the proposed changes are missing: labelling, alignment, and more detailed descriptions.

**Comment by densoutar** [comment]
Implementation does not correspond with mock-up:  
- ADs no longer displayed on page load
- There’s no differentiating information for ADs, e.g. “AD (Residential)” can refer to multiple completely different ADs.
- The value of the ADs are not displayed.
- Deselecting items causes them to move to the bottom of the list (unnecessarily confusing).
- Labels do not correspond to mock-up and are confusing, implying that the EF list items are ADs. 
- Unnecessarily bracketed numbers can be misinterpreted as [negative numbers](https://www.google.com.jm/search?q=brackets+as+negative+numbers+in+excel&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjD3LnT16vaAhWtq1kKHSd3CQAQ_AUICygC&biw=1758&bih=853#imgrc=E0OyeuGYrZ3sPM:).

**Comment by densoutar** [comment]
Updating mock-up based on most recent conversation with @gilgad:

<img width="1226" alt="screen shot 2018-04-09 at 11 22 43 pm - modified" src="https://user-images.githubusercontent.com/15874753/38575760-d14dd5fa-3cc1-11e8-81aa-2d9d0cd309f0.png">

- No column lines, with left-aligned headers
- Headers are a bit heavier than the ADs
- The ADs are prefixed with "AD - "; the EFs are prefixed with "EF - "
- The AD value is in the Variable Value column, along with its unit
- No load emissions button, assuming @matjames007 no longer needs it

**Illustrative purposes only; this is _not_ a pixel-perfect mock-up**

**Comment by densoutar** [comment]
@gilgad @matjames007:

- [ ] The year is missing from the AD label (refer to first mock-up); given that the data spans multiple years, this needs to be included.
- [ ] The units are also missing from the AD variable values.

This issue shouldn't be closed yet.
