### ISSUE TITLE
Duplicated EF

### ISSUE THREAD

**Issue by densoutar** [slashroots/undp-ghg-v2#71]
There's a pair of duplicate EFs in the Calculations page. If one is deselected, it disappears. 

<img width="1440" alt="duplicate efs" src="https://user-images.githubusercontent.com/15874753/36292981-b4e3da56-12a3-11e8-8b02-b818c0a2a9bf.png">

**Comment by gilgad** [comment]
Dirty data was accidentally introduced into the database and has since been removed. This should not be an issue going forward.

**Comment by paradoxxjm** [comment]
@denferg can you confirm that this was resolved

**Comment by densoutar** [comment]
This issue is likely related to the disappearing row described in the comment I made on 2018-04-08 on issue #72. If that's the case, then we still have a dirty data problem, @gilgad .

**Comment by densoutar** [comment]
Resolved
