### ISSUE TITLE
Saved calculations don't persist

### ISSUE THREAD

**Issue by densoutar** [slashroots/undp-ghg-v2#72]
After making changes on the Calculations page, and clicking Save Calculations, the data doesn't appear to be saved. Navigating away from the page and returning shows the data before modifications.

**Comment by densoutar** [comment]
**Test Results 2018-03-29**

Of the 5 selected, only 1 persisted. Three of the 5 had resulted in NaN calculations. One of the other 2 had “heads” selected as the unit.

The first attempt to deselect one of the test selections resulted in the deselection of the test selection immediately below it.

None of the “deselections” persisted.

If there are error states that prevent saving, then the user needs to be informed.

**Comment by densoutar** [comment]
**Test Results 2018-04-08**

Of the 5 selected, only 1 persisted, displaying the unit “tonne”, despite “kg” being selected.

The “deselections” persisted, but one of the deselected options disappeared from the table entirely.

If there are error states that prevent saving, then the user needs to be informed—NaN results are not saved, neither is there a warning.

_No ADs displayed on page load_
<img width="1440" alt="screen shot 2018-04-08 at 4 33 41 pm" src="https://user-images.githubusercontent.com/15874753/38473268-df32fa94-3b52-11e8-8cf9-f5eacd33356f.png">

_Starting condition: selections displayed on load_
<img width="1440" alt="screen shot 2018-04-08 at 5 09 18 pm" src="https://user-images.githubusercontent.com/15874753/38473269-df4b31fe-3b52-11e8-84cd-f7b56c38c39e.png">

_Test condition: selections made before clicking save_
<img width="1440" alt="screen shot 2018-04-08 at 5 11 12 pm" src="https://user-images.githubusercontent.com/15874753/38473270-df5f29c0-3b52-11e8-98e5-c94917796e76.png">

_Test result: after clicking save, after both selection and deselection tests. Notice the missing "Kerosene" row, as well as the lost (and modified) "LPG" selections_
<img width="1440" alt="screen shot 2018-04-08 at 5 31 25 pm" src="https://user-images.githubusercontent.com/15874753/38473271-df73af8a-3b52-11e8-8b27-8828f9f5d672.png">

**Comment by densoutar** [comment]
**Test Results 2018-04-11**

Of the 5 selected, only 1 persisted, but instead of displaying the selected unit, it displayed a different one.

Deselecting the test one selection that was "saved" persisted, as did deselecting the only selection under the AD that was present before the test (which retained the selected unit).

**Comment by densoutar** [comment]
@gilgad I see where some ADs have no EFs listed. Is this to avoid the NaN issue?

Does this mean I **don't** need to create an issue for save errors, since based on our last conversation, unit selection is optional?

**Comment by gilgad** [comment]
before we were getting NaN's because a  value was not saved in the database for the AD and the system attempted to do the calculation anyway. This doesn't happen anymore.

If EF's are not listed it is because the system did not find any associated EF's for that AD.

**Comment by densoutar** [comment]
Problem remains, plus application still allows me to navigate away from Calculations page while I have unsaved changes.

**Comment by densoutar** [comment]
**Test 2018-04-15**

_Issues_

- Was able to select 6 previously unselected EFs, chose units for only 3, and save selections without any errors being generated.
(Subsequent attempts to save selections without units triggered the Units Missing warning)
- Navigated away from and back to the Calculations screen. Saved selections did not persist.
- Was able to select previously unselected EFs and navigate away from page without the Unsaved Changes warning being displayed, especially when any of the second group of EFs were selected. 
(Trying this with only a selection from the first group or the third group triggered the warning)

**Comment by densoutar** [comment]
@gilgad While putting together the revised guide I observed that: 

- Attempting to save selected calculations triggers a Units Missing warning, even when all the units have been selected.
- Still being "prompted" to save even when unsaved selections have been deselected/unsaved deselections are reselected.
- Units are still missing for the ADs.
- The "name" of the AD (in the Activity Data / Emission Factors column) still missing the year at the end e.g. AD - Commercial/Institutional - Fuel Oil - 2010

**Comment by densoutar** [comment]
@gilgad 

**Test 2018-04-23**
Modified selections under "AD - Commercial/Institutional - Kerosene - 2010"

_Issues_

- Deselected previously selected EFs, OKed Unsaved Changes warning, and navigated away from page. Changes were still saved.
- When deselecting previously selected EFs they move unpredictably down the EF list.

_Passed_

- Selected previously unselected EFs and saved them.
- Attempt to navigate away from unsaved selections prompted Unsaved Changes warning.
- Attempt to save with no units selected prompted Units Missing warning.
- Selected previously unselected EFs, OKed Unsaved Changes warning, and navigated away from page. Changes were discarded.

**Comment by densoutar** [comment]
Resolved
