### ISSUE TITLE
"Add Category" and "Add Activity" buttons and dialogues are misleading

### ISSUE THREAD

**Issue by densoutar** [slashroots/undp-ghg-v2#74]
Both Categories and Activities pages have two tables, one of which is not editable. Buttons and their corresponding dialogues should be relabelled to "Add Local Categories" and "Add Local Activities" for clarity.

**Comment by paradoxxjm** [comment]
@denferg can you confirm that this has been resolved.

**Comment by densoutar** [comment]
@paradoxxjm resolved.
