### ISSUE TITLE
Confusing Add Category and Add Activity dialogues

### ISSUE THREAD

**Issue by densoutar** [slashroots/undp-ghg-v2#76]
The "Add Category" and "Add Activity" dialogues should be relabelled to "Add Local Category" and  to "Add Local Activity" respectively.

In the Category dialogue, changing a Category Code and then selecting an IPCC Category overwrites the user-generated Category Code. This should not happen. It might be best for the Category Code not to be auto-filled at all.

The Category Code field should be relabelled "Local Category Code".

The Category dialogue indicates required fields, but the Activity dialogue doesn't indicate which fields are required.

Attempt to add a category with an existing category code or add an activity leads to an error, error message doesn't indicate what is wrong or how it can be resolved.

<img width="1440" alt="screen shot 2018-02-15 at 8 36 54 pm" src="https://user-images.githubusercontent.com/15874753/36293884-9c8102b6-12aa-11e8-8635-38f22e6d290c.png">

**Comment by paradoxxjm** [comment]
@denferg confirm completion.

**Comment by densoutar** [comment]
@paradoxxjm incomplete.

**Comment by gilgad** [comment]
@denferg When the category code is changed, what is the expected behavior?
