### ISSUE TITLE
Changing inventory data via the Notes Panel changes unique identifier number to 0

### ISSUE THREAD

**Issue by densoutar** [slashroots/undp-ghg-v2#80]
Changing inventory data via the Notes Panel changes each modified row's unique identifier number to 0, even after the changes have been saved. Navigating away and returning to the page restores the numbering.

<img width="1440" alt="screen shot 2018-02-15 at 9 10 45 pm" src="https://user-images.githubusercontent.com/15874753/36294271-96111698-12ad-11e8-8f62-275e3827da17.png">

**Comment by denferg** [comment]
@gilgad This is the same thing that's now happening with inline editing. Funny it's happening now that the Notes panel is gone.

**Comment by densoutar** [comment]
@gilgad Inline editing doesn't affect the ID any more, but he ID still changes to zero when a correction is made via the Issues panel.

**Comment by densoutar** [comment]
Still unresolved

**Comment by densoutar** [comment]
Resolved
