### ISSUE TITLE
Uncertainty Values overlap with dropdown 

### ISSUE THREAD

**Issue by paradoxxjm** [slashroots/undp-ghg-v2#85]
When the activity figures on the screen exceed a specific number of values, they overlap with the drop-down menu. 

![ghg-calculations-textoverlap](https://user-images.githubusercontent.com/406181/36561567-091b63c6-17e2-11e8-9c20-a1a5cdbea9eb.png)

**Comment by densoutar** [comment]
@paradoxxjm resolved; please close this issue.
